repos:
  - repo: local
    hooks:
      - id: helm-lint
        name: Helm lint
        language: system
        entry: helm lint
        args: [charts/argus]
        files: ^charts/argus/
        pass_filenames: false
